### ISSUE TITLE
ошибка в программе

### ISSUE THREAD

**Issue by gozaltech** [beqabeqa473/GozalMusicMini#7]
Reported by Ирина Александрова
день добрый, со вчерашнего дня программа перестала воспроизводить музыку.
пишет вот что.
Error
Cannot play track at this 
timeSystem.Runtime.InteropServices.COMException (0xC00D001A): 
Исключение из HRESULT: 0xC00D001A
   в 
NAudio.MediaFoundation.MediaFoundationInterop.MFCreateSourceReaderF
romURL(String pwszURL, IMFAttributes pAttributes, IMFSourceReader& 
ppSourceReader)
   в 
NAudio.Wave.MediaFoundationReader.CreateReader(MediaFoundationRea
derSettings settings)
   в 
NAudio.Wave.MediaFoundationReader.Init(MediaFoundationReaderSettings
initialSettings)
   в NAudio.Wave.MediaFoundationReader..ctor(String file)
   в NAudio.Wave.AudioFileReader.CreateReaderStream(String fileName)
   в NAudio.Wave.AudioFileReader..ctor(String fileName)
   в GozalMusicMini.MainForm.PlaySound(String filename)
   в GozalMusicMini.MainForm.Playfile()
ОК

**Comment by Menelion** [comment]
Possible duplicate of #4?

**Comment by beqabeqa473** [comment]
добавил прокси в версии 0.4
